export interface AppointmentActionTypes {
    type: AppointmentActions;
    payload?: any;
  }
  export enum AppointmentActions {
    GET_APPOINTMENT_LIST = "GET_APPOINTMENT_LIST",
    SET_APPOINTMENT_LIST = "SET_APPOINTMENT_LIST",
    RESET_APPOINTMENT_LIST = "RESET_APPOINTMENT_LIST",
    APPOINTMENT_LIST_LOADER = "APPOINTMENT_LIST_LOADER",
    GET_VIEW_APPONTMENT = "GET_VIEW_APPONTMENT",
    SET_VIEW_APPONTMENT = "SET_VIEW_APPONTMENT",
    VIEW_APPONTMENT_LOADER = "VIEW_APPONTMENT_LOADER",
    RESCHEDULE_APPONTMENT= "RESCHEDULE_APPONTMENT",
    RESCHEDULE_APPONTMENT_LOADER= "RESCHEDULE_APPONTMENT_LOADER",
    RESCHEDULE_APPONTMENT_SUCCESS= "RESCHEDULE_APPONTMENT_SUCCESS",
    RAISE_DISPUTE = "RAISE_DISPUTE",
    GIV_FEEDBACK = "GIV_FEEDBACK",
    UPDATE_FEEDBACK = "UPDATE_FEEDBACK",
    GET_FEEDBACK_LIST = "GET_FEEDBACK_LIST",
    SET_FEEDBACK_LIST = "SET_FEEDBACK_LIST",
    SET_FEEDBACK_LIST_LOADER = "SET_FEEDBACK_LIST_LOADER",
    RESET_FEEDBACK_LIST = "RESET_FEEDBACK_LIST",
    SET_FEEDBACK_LOADER = "SET_FEEDBACK_LOADER",
}
 