export interface ChatActionTypes {
    type: ChatActions;
    payload?: any;
  }

  export enum ChatActions {
    QUOTATION_UPDATE_STATUS = "QUOTATION_UPDATE_STATUS",
    ACCEPT_QUOTATION_LOADER = "ACCEPT_QUOTATION_LOADER",
    REJECT_QUOTATION_LOADER = "REJECT_QUOTATION_LOADER",
    ORDER_STATUS_UPDATE = "ORDER_STATUS_UPDATE",
    SET_ORDER_STATUS = "SET_ORDER_STATUS",
    ORDER_STATUS_UPDATE_LOADER = "ORDER_STATUS_UPDATE_LOADER",
    CREATE_CHANNEL = "CREATE_CHANNEL",
    CREATE_CHANNEL_LOADING = "CREATE_CHANNEL_LOADING",
    SEND_FIRST_MSG_NOTIFICATION = "SEND_FIRST_MSG_NOTIFICATION"
 }
 