export interface CompanyUserTypes {
  type: CompanyUserAction;
  payload?: any;
}

export enum CompanyUserAction {
  VERIFY_LINK = "VERIFY_LINK",
  SET_VERIFY_LINK_LOADER = "SET_VERIFY_LINK_LOADER",
  UPDATE_COMPANY_PROFILE_DATA = "UPDATE_COMPANY_PROFILE_DATA",
  GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST",
  SET_EMPLOYEE_LIST = "SET_EMPLOYEE_LIST",
  RESET_EMPLOYEE_LIST = "RESET_EMPLOYEE_LIST",
  SET_EMPLOYEE_LIST_LOADER = "SET_EMPLOYEE_LIST_LOADER",
  EMPLOYEE_INVITATION = "EMPLOYEE_INVITATION",
  UPDATE_EMPLOYEE_STATUS = "UPDATE_EMPLOYEE_STATUS",
  SET_UPDATE_EMPLOYEE_STATUS = "SET_UPDATE_EMPLOYEE_STATUS",
  EMPLOYEE_INVITATION_SUCCESS = "EMPLOYEE_INVITATION_SUCCESS",
  EMPLOYEE_INVITATION_LOADER = "EMPLOYEE_INVITATION_LOADER",
  GET_COMPANY_PAYMENT_HISTORY = "GET_COMPANY_PAYMENT_HISTORY",
  SET_COMPANY_PAYMENT_HISTORY = "SET_COMPANY_PAYMENT_HISTORY",
  SET_COMPANY_PAYMENT_HISTORY_LOADER = "SET_COMPANY_PAYMENT_HISTORY_LOADER",
  SET_COMPANY_PAYMENT_HISTORY_METAPARAMS = "SET_COMPANY_PAYMENT_HISTORY_METAPARAMS",
  RESET_COPMANY_PAYMENT_HISTORY = "RESET_COPMANY_PAYMENT_HISTORY",
  COPMANY_DOWNLOAD_INVOICE = "COPMANY_DOWNLOAD_INVOICE",
  COPMANY_DOWNLOAD_INVOICE_LOADING = "COPMANY_DOWNLOAD_INVOICE_LOADING",
  GET_COMPANY_WALLET_LEDGER_HISTORY= "GET_COMPANY_WALLET_LEDGER_HISTORY",
  SET_COMPANY_WALLET_LEDGER_HISTORY= "SET_COMPANY_WALLET_LEDGER_HISTORY",
  SET_COMPANY_WALLET_LEDGER_HISTORY_LOADER= "SET_COMPANY_WALLET_LEDGER_HISTORY_LOADER",
  SET_COMPANY_WALLET_LEDGER_HISTORY_METAPARAMS= "SET_COMPANY_WALLET_LEDGER_HISTORY_METAPARAMS",
  RESET_COPMANY_WALLET_LEDGER_HISTORY= "RESET_COPMANY_WALLET_LEDGER_HISTORY",
  GET_COMPANY_DASHBOARD_KPI = "GET_COMPANY_DASHBOARD_KPI",
  SET_COMPANY_DASHBOARD_KPI = "SET_COMPANY_DASHBOARD_KPI",
  EMPTY_WALLET_AMOUNT = "EMPTY_WALLET_AMOUNT",
  EMPTY_WALLET_AMOUNT_LOADER = "EMPTY_WALLET_AMOUNT_LOADER",
 }
 