export interface FundManagementActionsTypes {
  type: FundManagementActions;
  payload?: any;
}

export enum FundManagementActions {
  ADD_FUND = "ADD_FUND",
  ADD_FUND_LOADER = "ADD_FUND_LOADER",
  ALLOCATE_FUND = "ALLOCATE_FUND",
  ALLOCATE_FUND_SUCCESS = "ALLOCATE_FUND_SUCCESS",
  VERIFY_FUND = "VERIFY_FUND",
  GET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS = "GET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS",
  SET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS_LOADER = "SET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS_LOADER",
  SET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS = "SET_EMPLOYEE_LIST_FOR_FUND_ALLOCATIONS",
  
}
